name: environment
channels:
    - pytorch
    - defaults
dependencies:
    - python>=3.6
    - pytorch=1.7.1
    - torchvision=0.8.2
    - cudatoolkit=10.2
    - ignite=0.4.2
    - tqdm
    - tensorboard
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - scikit-learn
